/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_testjni_jni_JniUtils */

#ifndef _Included_com_testjni_jni_JniUtils
#define _Included_com_testjni_jni_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_testjni_jni_JniUtils
 * Method:    getWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_testjni_jni_JniUtils_getWorld
  (JNIEnv *, jobject);

/*
 * Class:     com_testjni_jni_JniUtils
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_testjni_jni_JniUtils_getMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
